export interface PCComponent {
  id: string;
  name: string;
  category: 'core' | 'storage' | 'cooling' | 'power' | 'extras';
  slotId: string;
  difficulty: 'easy' | 'medium' | 'hard';
  description: string;
  tip: string;
}
export const PC_COMPONENTS: PCComponent[] = [
  // Core Components
  {
    id: 'cpu',
    name: 'AMD Ryzen 9 7950X3D',
    category: 'core',
    slotId: 'cpu-socket',
    difficulty: 'medium',
    description: 'High-performance 16-core processor with 3D V-Cache technology for gaming and productivity.',
    tip: 'Align the golden triangle on the CPU corner with the socket marker. Never force the CPU into place.',
  },
  {
    id: 'thermal-paste',
    name: 'Arctic MX-6 Thermal Paste',
    category: 'core',
    slotId: 'thermal-paste',
    difficulty: 'easy',
    description: 'Premium thermal compound for optimal heat transfer between CPU and cooler.',
    tip: 'Apply a pea-sized amount to the center of the CPU. The cooler pressure will spread it evenly.',
  },
  {
    id: 'cpu-cooler',
    name: 'Noctua NH-D15',
    category: 'cooling',
    slotId: 'cpu-cooler',
    difficulty: 'medium',
    description: 'Dual-tower air cooler with exceptional cooling performance and whisper-quiet operation.',
    tip: 'Mount the backplate first, then secure the cooler with even pressure on all mounting screws.',
  },
  {
    id: 'ram-1',
    name: 'G.Skill Trident Z5 RGB (1)',
    category: 'core',
    slotId: 'ram-slot-1',
    difficulty: 'easy',
    description: 'High-speed DDR5-6000 memory module with stunning RGB lighting.',
    tip: 'Install in slots 2 and 4 first for dual-channel. Align the notch and press firmly until clips click.',
  },
  {
    id: 'ram-2',
    name: 'G.Skill Trident Z5 RGB (2)',
    category: 'core',
    slotId: 'ram-slot-2',
    difficulty: 'easy',
    description: 'High-speed DDR5-6000 memory module with stunning RGB lighting.',
    tip: 'Check motherboard manual for optimal slot configuration for best performance.',
  },
  {
    id: 'ram-3',
    name: 'G.Skill Trident Z5 RGB (3)',
    category: 'core',
    slotId: 'ram-slot-3',
    difficulty: 'easy',
    description: 'High-speed DDR5-6000 memory module with stunning RGB lighting.',
    tip: 'Ensure the RAM is fully seated - both clips should snap into place automatically.',
  },
  {
    id: 'ram-4',
    name: 'G.Skill Trident Z5 RGB (4)',
    category: 'core',
    slotId: 'ram-slot-4',
    difficulty: 'easy',
    description: 'High-speed DDR5-6000 memory module with stunning RGB lighting.',
    tip: 'For 4 sticks, all slots will be populated. Verify XMP/EXPO profile in BIOS after boot.',
  },
  {
    id: 'gpu',
    name: 'NVIDIA GeForce RTX 4090',
    category: 'core',
    slotId: 'pcie-x16',
    difficulty: 'medium',
    description: 'Flagship graphics card with 24GB VRAM for 4K gaming and content creation.',
    tip: 'Remove PCIe slot covers, align with slot, and press firmly. Use a GPU support bracket due to weight.',
  },
  // Storage
  {
    id: 'nvme-ssd',
    name: 'WD Black SN850X 2TB',
    category: 'storage',
    slotId: 'nvme-slot',
    difficulty: 'easy',
    description: 'Ultra-fast PCIe Gen4 NVMe SSD with up to 7,300 MB/s read speeds.',
    tip: 'Insert at 30° angle into M.2 slot, then press down and secure with the mounting screw.',
  },
  {
    id: 'sata-ssd',
    name: 'Samsung 870 EVO 1TB',
    category: 'storage',
    slotId: 'sata-ssd',
    difficulty: 'easy',
    description: 'Reliable SATA SSD for secondary storage with excellent endurance.',
    tip: 'Mount in 2.5" bay, connect SATA data cable to motherboard and power cable from PSU.',
  },
  {
    id: 'hdd',
    name: 'Seagate Barracuda 4TB',
    category: 'storage',
    slotId: 'hdd-bay',
    difficulty: 'easy',
    description: 'High-capacity hard drive for mass storage of games, media, and backups.',
    tip: 'Secure in 3.5" bay with screws. HDDs are sensitive to vibration - ensure firm mounting.',
  },
  // Power
  {
    id: 'psu',
    name: 'Corsair RM850x',
    category: 'power',
    slotId: 'psu-bay',
    difficulty: 'medium',
    description: '850W 80+ Gold modular power supply with silent operation.',
    tip: 'Fan should face down if case has bottom ventilation. Connect only needed modular cables.',
  },
  {
    id: 'atx-24pin',
    name: '24-Pin ATX Power Cable',
    category: 'power',
    slotId: 'atx-24pin',
    difficulty: 'easy',
    description: 'Main motherboard power connector providing primary power to the system.',
    tip: 'Align the clip with the socket and push firmly until it clicks. This powers the motherboard.',
  },
  {
    id: 'eps-8pin',
    name: '8-Pin EPS CPU Cable',
    category: 'power',
    slotId: 'eps-8pin',
    difficulty: 'easy',
    description: 'CPU power connector delivering dedicated power to the processor.',
    tip: 'Located near the CPU socket. Route cable behind motherboard tray for clean cable management.',
  },
  {
    id: '12vhpwr',
    name: '12VHPWR GPU Cable',
    category: 'power',
    slotId: '12vhpwr',
    difficulty: 'medium',
    description: '16-pin power connector for high-power graphics cards like RTX 4090.',
    tip: 'Ensure full insertion - partial connection can cause melting. Avoid sharp cable bends.',
  },
  {
    id: 'sata-cable-1',
    name: 'SATA Data Cable (Red)',
    category: 'power',
    slotId: 'sata-cable-1',
    difficulty: 'easy',
    description: 'Data cable connecting storage drives to the motherboard.',
    tip: 'Connect one end to drive, other to motherboard SATA port. L-shaped connector for tight spaces.',
  },
  {
    id: 'sata-cable-2',
    name: 'SATA Data Cable (Black)',
    category: 'power',
    slotId: 'sata-cable-2',
    difficulty: 'easy',
    description: 'Data cable connecting storage drives to the motherboard.',
    tip: 'Use SATA ports 1-2 for boot drives for best compatibility.',
  },
  // Cooling
  {
    id: 'fan-front-1',
    name: 'Corsair RGB Fan (Front 1)',
    category: 'cooling',
    slotId: 'fan-front-1',
    difficulty: 'easy',
    description: '120mm RGB case fan for front intake airflow.',
    tip: 'Mount as intake (blowing into case). Arrow on frame shows airflow direction.',
  },
  {
    id: 'fan-front-2',
    name: 'Corsair RGB Fan (Front 2)',
    category: 'cooling',
    slotId: 'fan-front-2',
    difficulty: 'easy',
    description: '120mm RGB case fan for front intake airflow.',
    tip: 'Stack with first front fan for maximum intake. Connect to fan header or hub.',
  },
  {
    id: 'fan-rear',
    name: 'Corsair RGB Fan (Rear)',
    category: 'cooling',
    slotId: 'fan-rear',
    difficulty: 'easy',
    description: '120mm RGB case fan for rear exhaust.',
    tip: 'Mount as exhaust (blowing out of case). Creates positive airflow with front intakes.',
  },
  {
    id: 'fan-top',
    name: 'Corsair RGB Fan (Top)',
    category: 'cooling',
    slotId: 'fan-top',
    difficulty: 'easy',
    description: '120mm RGB case fan for top exhaust.',
    tip: 'Top fans work best as exhaust since heat rises naturally.',
  },
  {
    id: 'aio-pump',
    name: 'NZXT Kraken Z73 Pump',
    category: 'cooling',
    slotId: 'aio-pump',
    difficulty: 'hard',
    description: 'AIO liquid cooler pump head with LCD display showing temps and custom graphics.',
    tip: 'Apply thermal paste to CPU first. Mount pump with tubes at bottom or side, never top.',
  },
  {
    id: 'radiator-360',
    name: '360mm AIO Radiator',
    category: 'cooling',
    slotId: 'radiator-360',
    difficulty: 'medium',
    description: 'Triple 120mm radiator for the AIO cooler providing excellent heat dissipation.',
    tip: 'Best mounted at top or front. Ensure tubes reach pump without kinking.',
  },
  // Extras
  {
    id: 'cmos-battery',
    name: 'CMOS Battery (CR2032)',
    category: 'extras',
    slotId: 'cmos-battery',
    difficulty: 'easy',
    description: 'Coin cell battery that maintains BIOS settings and system clock.',
    tip: 'Usually pre-installed. Replace if BIOS settings reset or clock loses time.',
  },
  {
    id: 'io-shield',
    name: 'Motherboard I/O Shield',
    category: 'extras',
    slotId: 'io-shield',
    difficulty: 'easy',
    description: 'Metal plate that covers the rear I/O ports and provides EMI shielding.',
    tip: 'Install BEFORE the motherboard! Push from inside the case until all corners click.',
  },
  {
    id: 'front-panel',
    name: 'Front Panel Connectors',
    category: 'extras',
    slotId: 'front-panel',
    difficulty: 'hard',
    description: 'Tiny cables for power button, reset button, and LED indicators.',
    tip: 'Check motherboard manual for exact pin layout. Use a flashlight and magnifier if needed.',
  },
  {
    id: 'usb-header',
    name: 'USB 3.2 Internal Header',
    category: 'extras',
    slotId: 'usb-header',
    difficulty: 'medium',
    description: 'Internal connector for front panel USB 3.2 ports.',
    tip: 'Blue 19-pin connector. Align the notch and connect to motherboard USB 3.0 header.',
  },
  {
    id: 'wifi-card',
    name: 'Intel AX211 WiFi Card',
    category: 'extras',
    slotId: 'wifi-slot',
    difficulty: 'medium',
    description: 'WiFi 6E and Bluetooth 5.3 adapter for wireless connectivity.',
    tip: 'Install in M.2 WiFi slot or PCIe x1. Connect antenna cables to gold connectors.',
  },
  {
    id: 'sound-card',
    name: 'ASUS Xonar AE Sound Card',
    category: 'extras',
    slotId: 'sound-card',
    difficulty: 'medium',
    description: 'Dedicated sound card for audiophiles with premium DAC and amplifier.',
    tip: 'Install in any PCIe x1 or larger slot. Install drivers for full functionality.',
  },
  {
    id: 'rgb-hub',
    name: 'Corsair Commander Pro',
    category: 'extras',
    slotId: 'rgb-hub',
    difficulty: 'medium',
    description: 'RGB and fan controller hub for centralized lighting and cooling management.',
    tip: 'Mount in hidden location. Connect to internal USB header and SATA power.',
  },
  {
    id: 'vrm-heatsink',
    name: 'VRM Heatsink',
    category: 'extras',
    slotId: 'vrm-heatsink',
    difficulty: 'hard',
    description: 'Passive cooling for voltage regulator modules ensuring stable power delivery.',
    tip: 'Usually pre-installed on motherboard. Ensure good contact with thermal pads.',
  },
  {
    id: 'bios-chip',
    name: 'BIOS/UEFI Chip',
    category: 'extras',
    slotId: 'bios-chip',
    difficulty: 'hard',
    description: 'Firmware chip containing the BIOS/UEFI code that initializes hardware on boot.',
    tip: 'Do not remove! Only relevant when updating BIOS or troubleshooting boot issues.',
  },
];
